services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
    container_name: go-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      ENABLE_HTTPS: "true"

volumes:
  mysql-data: