services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/seed/init-prod.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile-prod
    container_name: go-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password

  test-db:
    image: mysql:8
    container_name: mysql-test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /tmp/mysql-data:/var/lib/mysql
      - ./database/seed/init-test.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: --tmpdir=/tmp

  test-runner:
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile-test
    container_name: go-test-runner
    volumes:
      - .:/app
    environment:
      DB_HOST: mysql-test-db
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - test-db
    command: go test ./... -v

volumes:
  mysql-data: